# --- General options --- #
url: 'https://talesoforlandia.com'
baseurl: ''

title: 'Tales of Orlandia'
description: 'A brief history of the Orlandia story thus far'

# --- Navigation bar options --- #
navbar-links:
  About: 'about'
  Timeline: 'timeline'
  Orlandia History: 'history'
  AFO Home: 'https://animefestivalorlando.com'

history-pages:
  - name: Swords of Orlandia
    href: 'history/swords'
    year: 2007
  - name: Swords of Orlandia II
    href: 'history/swords-2'
    year: 2008
  - name: Swords of Orlandia III
    href: 'history/swords-3'
    year: 2009
  - name: Skies of Orlandia
    href: 'history/skies'
    year: 2010
  - name: Conquerors of Neo-Orlandia
    href: 'history/neo'
    year: 2011
  - name: Wyldes of Orlandia
    href: 'history/wyldes'
    year: 2012
  - name: Rocket Rangers of Orlandia
    href: 'history/rocket'
    year: 2013
  - name: Rocket Rangers of Orlandia II
    href: 'history/rocket-2'
    year: 2014
  - name: Curse of the White Witch
    href: 'history/witch'
    year: 2015
  - name: Crisis on Infinite Orlandias
    href: 'history/crisis'
    year: 2016
  - name: School Spirits
    href: 'history/spirits'
    year: 2017
  - name: Seas of Orlandia
    href: 'history/seas'
    year: 2018
  - name: Syndicates of Cyber-Orlandia
    href: 'history/syndicates'
    year: 2019
  - name: King's Ransom
    href: 'history/kings-ransom'
    year: 2022
  - name: Chrono Conflict
    href: 'history/chrono-conflict'
    year: 2023

avatar-ext: 'https://statics.orlandia.talesoforlandia.com/logos/avatar-icon.png'

# --- Footer options --- #
author:
  name: Anime Festival Orlando
  email: 'tales@talesoforlandia.com'
  facebook: CodexOrlandia
  twitter: TalesOfOrlandia
  youtube: '@talesoforlandia'

footer-links-active:
  rss: true
  facebook: true
  email: true
  twitter: true
  youtube: true
  google-plus: true

share-links-active:
  twitter: true
  facebook: true
  email: true

url-pretty: 'TalesOfOrlandia.com'

# --- Misc --- #
# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# Fill in your Google Analytics ID to track your website using GA
google_analytics: 'UA-101259382-1'

# Google Tag Manager ID
#gtm: ""

# Facebook App ID
fb_app_id: '758530351248066'

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: '-'

# --- Don't need to touch anything below here (but you can if you want) --- #
timezone: 'America/New_York'
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      comments: true # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  - scope:
      path: '' # all files
    values:
      layout: 'page'
      show-avatar: true

# Use tags pages (not recommended if you are deploying via GitHub pages, only set to true if deploying locally with ruby)
link-tags: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'post'
      - name: 'title'
        field:
          element: 'text'
          label: 'Post title'
          placeholder: 'Title'
          alterable: true
      - name: 'subtitle'
        field:
          element: 'textarea'
          label: 'Subtitle'
          placeholder: 'A description of your post.'
          alterable: true
      - name: 'date'
        field:
          element: 'text'
          label: 'Date'
          help: 'Enter date of post.'
          placeholder: 'yyyy-mm-dd'
          alterable: true
      - name: 'image'
        field:
          element: 'text'
          label: 'Image'
          help: 'Add a thumbnail image to your post.'
          placeholder: 'Thumbnail'
          alterable: true
      - name: 'published'
        field:
          element: 'checkbox'
          label: 'Publish'
          help: 'Check to publish post, uncheck to hide.'

plugins:
  - jekyll-paginate

sass:
  sass_dir: _sass
  style: compressed
